### ISSUE TITLE
审批流程可以用吗？

### ISSUE THREAD

**Issue by 107295472** [daiyekun/DevAdmin#1]

**Comment by daiyekun** [comment]
最近，审批流我在抽时间弄，目前不可以。但是只是简单审批功能哟。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月6日(周二) 下午2:32
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [daiyekun/DevAdmin] 审批流程可以用吗？ (Issue #1)

**Comment by 107295472** [comment]
这个是用的java的flowable吗

**Comment by daiyekun** [comment]
不是，后台.net自己写的。前台画图用滴滴出品logicflow





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月6日(周二) 下午2:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [daiyekun/DevAdmin] 审批流程可以用吗？ (Issue #1)




 
这个是用的java的flowable吗

**Comment by daiyekun** [comment]
简单审批已经可以满足了
